apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: customer-profile
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: customer-profile
    apps.tanzu.vmware.com/has-tests: "true"
    apis.apps.tanzu.vmware.com/register-api: "true"
spec:
  serviceClaims:
    - name: db
      ref:
        apiVersion: sql.tanzu.vmware.com/v1
        kind: Postgres
        name: customer-profile-database
  build:
    env:
      - name: BP_JVM_VERSION
        value: "11"
  params:
    - name: testing_pipeline_matching_labels
      value:
        apps.tanzu.vmware.com/pipeline: test-with-test-containers
#        apps.tanzu.vmware.com/language: blah
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: api_descriptor
      value:
        type: openapi
        location: 
          path: "/api-docs"
        owner: john@doe.com
        system: genz
        description: a simple test
  source:
    git:
      ref:
        branch: main
      url: https://github.com/berinle/java-rest-service.git
      #subPath: java-rest-service
